# Generated by Django 3.2.4 on 2021-06-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Deepak's Blogs", max_length=255),
        ),
    ]
